import Authprovider from "@/components/Authprovider/Authprovider";
import { Footer } from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { FooterLinks } from "@/components/FooterLinks";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { FaPhoneAlt, FaWhatsapp } from "react-icons/fa";
import Link from "next/link";
import Popup from "@/components/Popup";
import Script from "next/script";

export async function generateMetadata() {
  return {
    title: "GoEdu",
    description: "Generated by create next app",
    icons: [{ rel: "icon", url: "/goEdulogo.svg" }],
    other: {
      "application-name": "GoEdu",
      "keywords": "education, GoEdu, online learning",
      "viewport": "width=device-width, initial-scale=1"
    },
  };
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="r2lMDe_0IlOZt1AmGXidtsjJSRhI8RkQd6jZs-kDoPk" />
        <meta name="google-site-verification" content="1OK7AS59HEPlQx7IVp_HdfQIX6PApYm5hRxOTlD9aYc" />
        <meta name="google-site-verification" content="qgn6MqFJA53sQvYVhpT70fVxndZfM0zTF1uSq0Uiy1g" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-ZB62BEDP2"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-ZB62BEDP2');
          `}
        </Script>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-YKMGLKBTB1"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-YKMGLKBTB1');
          `}
        </Script>
      </head>
      <body className="overflow-x-hidden">
        <ToastContainer />
        <Authprovider>
          <Navbar />
          <Popup />
          {children}
          <Footer />
          <FooterLinks />
        </Authprovider>
        <div className="fixed bottom-4 left-4 z-50">
          <Link href="tel:+9557695360" aria-label="Phone">
            <button className="bg-blue-500 text-white p-3 rounded-full shadow-lg hover:bg-blue-600">
              <FaPhoneAlt className="text-2xl" />
            </button>
          </Link>
        </div>
        <div className="fixed bottom-4 right-4 z-50">
          <Link href="https://wa.me/9557695360" aria-label="WhatsApp">
            <button className="bg-green-500 text-white p-3 rounded-full shadow-lg hover:bg-green-600">
              <FaWhatsapp className="text-3xl" />
            </button>
          </Link>
        </div>
      </body>
    </html>
  );
}
