import Authprovider from "@/components/Authprovider/Authprovider";
import { Footer } from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { FooterLinks } from "@/components/FooterLinks";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Script from "next/script";
export async function generateMetadata() {
  return {
    title: "GoEdu",
    description: "Generated by create next app",
    icons: [{ rel: "icon", url: "/goEdulogo.svg" }],
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
         <head>
        <meta
          name="google-site-verification"
          content="qgn6MqFJA53sQvYVhpT70fVxndZfM0zTF1uSq0Uiy1g"
        />
        <meta
          name="google-site-verification"
          content="1OK7AS59HEPlQx7IVp_HdfQIX6PApYm5hRxOTlD9aYc"
        />
     
        <Script
         
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-51DFFSG7NZ"
        ></Script>
        <Script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-51DFFSG7NZ');
            `,
          }}
          async
          
        />
      </head>
      <body className=" overflow-x-hidden">
        <ToastContainer />
        <Authprovider>
          <Navbar />
          {/* <Booking /> */}
          {children}
          <Footer />
          <FooterLinks />
        </Authprovider>
        <script src="https://cdn.tailwindcss.com"></script>
      <script src="https://kwesforms.com/v2/kf-script.js" defer></script>
      </body>
    </html>
  );
}
